#if !defined(compiler_h)
#define compiler_h

#include "chunk.h"
#include "scanner.h"

/**
 * compile - takes in a string and generates its corresponding bytecode.
 * @source: input string to be compiled.
 * @chunk: pointer to a 'Chunk' type where the generated bytecode will be stored.
 * @bool: whether or not the compilation was successful.
 */
bool compile(char const* source, Chunk* chunk);

#endif
